<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="capellaextension" nsURI="http://www.polarsys.org/capella/extension/genchain/0.8.0"
    nsPrefix="CapellaExtension">
  <eClassifiers xsi:type="ecore:EClass" name="CapellaEmfGeneration" eSuperTypes="platform:/plugin/org.polarsys.kitalpha.emde.genchain/model/eMDE_Extension.ecore#//EmdeGeneration"/>
  <eClassifiers xsi:type="ecore:EClass" name="CapellaCdoEmfGeneration" eSuperTypes="platform:/plugin/org.polarsys.kitalpha.emde.genchain/model/eMDE_Extension.ecore#//EmdeCdoGeneration"/>
</ecore:EPackage>
