<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="connectorextension" nsURI="http://www.polarsys.org/capella/cdoxml/genchain/extension/connector/1.0.0"
    nsPrefix="connectorextension">
  <eClassifiers xsi:type="ecore:EClass" name="ConnectorGeneration" eSuperTypes="platform:/plugin/org.eclipse.egf.portfolio.genchain/model/generationChain.ecore#//EcoreElement platform:/plugin/org.eclipse.egf.portfolio.genchain/model/generationChain.ecore#//PluginProvider">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="addConnectorEAnnotations"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral="false"/>
  </eClassifiers>
</ecore:EPackage>
